### ISSUE TITLE
api down?

### ISSUE THREAD

**Issue by whosFritz** [olech2412/EssensGetter-API#22]
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.41 (Ubuntu) Server at api.olech2412.de Port 443

**Comment by olech2412** [comment]
Sehr geehrter Herr Schubert,

aktuell überarbeiten wir unsere Systeme. Dadurch kann es hin und wieder zu einem Neustart der Anwendung kommen oder eine Version der API mit der ihre App noch nicht kompatibel ist läuft aktuell.
Wir arbeiten mit Hochdruck daran unsere Arbeiten abzuschließen.

Mit freundlichen Grüßen,
Ole Christoph ~ CEO - EssensGetter Infrastructure

**Comment by whosFritz** [comment]
Sehr geehrter Herr Christoph,

vielen Danke für die schnelle Auskunft. Unsere top Ingenieure haben grade bemerkt, dass die Verbindung der MensiMates Web App und mobile App einen Fehler auswirft. Unsere Top Software Entwickler werden umgehend Änderungen an der CodeBase vornehmen.
Bitte lassen Sie uns gegebenfalls informationen zu der Schnittstelle zukommen sobald, Sie genauere Informationen haben.
Vielen Dank


Viele Grüße
Fritz Schubert - CEO MensiMates

**Comment by whosFritz** [comment]
Sehr geehrter Herr Christoph,

Ihre Nachricht wurde bei uns mit Freude empfangen und die Software-Entwickler unserer Abteilung werden sich sofort daran setzen, die Schnittstellenabfrage seitens unser auf Vordermann zu bringen.
Voraussichtlich werden diese Änderungen und andere am Freitag vorgenommen. Eine Version 1.2 im Google Playstore ist ab Dienstag dem 13. Juni 2023 zu erwarten.


Anmerkungen:
- das mit dem XML Header Annotation schaue ich mir an
- Danke an Len für sein wachsames Auge
