### ISSUE TITLE
404 Response

### ISSUE THREAD

**Issue by olech2412** [olech2412/EssensGetter-API#8]
Respond to unknow requests

**Comment by whosFritz** [comment]
As a fullstack senior springboot java software engineer senior spring django unchained,
I would like to contribute to this issue. Please tell me more about the bug please
`System.out.println("Django");`

**Comment by olech2412** [comment]
@whosFritz is in progress

**Comment by whosFritz** [comment]
![issue close meme](https://github.com/olech2412/EssensGetter-API/assets/97552289/a8171cb7-a1b2-4d5a-8f9d-7303245e9ec1)
